require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'


if "#{ENV['KLIPPA_SCANNER_SDK_USERNAME']}" == ""
  ENV['KLIPPA_SCANNER_SDK_USERNAME'] = '{your-username}'
end

if "#{ENV['KLIPPA_SCANNER_SDK_PASSWORD']}" == ""
  ENV['KLIPPA_SCANNER_SDK_PASSWORD'] = '{your-password}'
end


use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'KlippaCapacitorKlippaScannerSdk', :path => '../../..'
end

target 'App' do

  if "#{ENV['KLIPPA_SCANNER_SDK_URL']}" == ""
    file_path = File.expand_path('../../node_modules/@klippa/capacitor-klippa-scanner-sdk/ios/Plugin/.sdk_repo', __dir__)
    ENV['KLIPPA_SCANNER_SDK_URL'] = File.read(file_path).strip
  end

  if "#{ENV['KLIPPA_SCANNER_SDK_VERSION']}" == ""
    file_path = File.expand_path('../../node_modules/@klippa/capacitor-klippa-scanner-sdk/ios/Plugin/.sdk_version', __dir__)
    ENV['KLIPPA_SCANNER_SDK_VERSION'] = File.read(file_path).strip
  end

  pod 'Klippa-Scanner', podspec: "#{ENV['KLIPPA_SCANNER_SDK_URL']}/#{ENV['KLIPPA_SCANNER_SDK_USERNAME']}/#{ENV['KLIPPA_SCANNER_SDK_PASSWORD']}/KlippaScanner/#{ENV['KLIPPA_SCANNER_SDK_VERSION']}.podspec"

  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
